IspitiNRAKO/Controllers/MojIspitController.cs
using IspitiNRAKO.Models;
using IspitiNRAKO.Repozitorij;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IspitiNRAKO.Controllers
{
    public class MojIspitController : Controller
    {

        private IspitiEntities db = new IspitiEntities();
        Random rnd = new Random(DateTime.Now.Millisecond);
        KorisnikRepozitorij repoKorisnik = new KorisnikRepozitorij();
        MojIspitRepozitorij repoMojIspit = new MojIspitRepozitorij();
        IspitRepozitorij repoIspit = new IspitRepozitorij();
        PitanjeRepozitorij repoPitanje = new PitanjeRepozitorij();


        // GET: MojIspit
        public ActionResult Index()
        {

            int userid = Int32.Parse(Session["UserID"].ToString());


            Korisnik korisnik = repoKorisnik.FindById(userid);


            List<Grupa> grupe = repoMojIspit.GetGrupe(userid);

            List<Ispit> ispiti = new List<Ispit>();

            foreach (Grupa grupa in grupe)
            {
                int grupaid = grupa.IdGrupa;


                List<Ispit> isp = repoMojIspit.GetIspiti(grupaid);

                ispiti.AddRange(isp);
            }

            

            return View(ispiti);
        }

        public ActionResult Start(int? id)
        {
            Ispit ispit = repoIspit.FindById(id);
            IspitManager im = StartIspit(ispit);

            if (Session["EndDate"] == null)
            {
                Session["EndDate"] = DateTime.Now.AddMinutes(ispit.Trajanje).ToString("dd-MM-yyyy h:mm:ss tt");
            }
            ViewBag.EndDate = Session["EndDate"];

            return View(im);
            
        }

        public IspitManager StartIspit(Ispit ispit)
        {

            IspitManager im = new IspitManager();
            im.IdIspit = ispit.IdIspit;
            Session["IdIspit"] = im.IdIspit;

            foreach (IspitSkupPitanja item in ispit.IspitSkupPitanjas)
            {
                SkupPitanja skup = item.SkupPitanja;
                int broj = item.BrojPitanja;
                List<Pitanje> pitanjaStart = skup.Pitanjes.ToList();
                List<Pitanje> pitanjaEnd = pitanjaStart.OrderBy(x => rnd.Next()).Take(broj).ToList();
                foreach (Pitanje pit in pitanjaEnd)
                {
                    PitanjeManager pm = new PitanjeManager();
                    pm.Pitanje = pit;
                    pm.Odgovoreno = 0;
                    pm.Tocno = 0;
                    im.Pitanja.Add(pm);
                }
            }

            var firstElement = im.Pitanja.First();
            ViewBag.IdPitanje = firstElement.Pitanje.IdPitanje;
            Session["Ispit"] = im;
            Session["Kraj"] = 0;

            
            return im;

        }

        public ActionResult Odgovori(int? id)
        {
            IspitManager im = Session["Ispit"] as IspitManager;

            ViewBag.IdPitanje = id;
            Pitanje pitanje = repoPitanje.FindById(id);
            ViewBag.Tekst = pitanje.Tekst;

            return View(im);

        }

        [HttpPost]
        public ActionResult Odgovori(FormCollection fc)
        {

            int idPitanje = Int32.Parse(Request.Form["idPitanje"]);
            IspitManager im = Session["Ispit"] as IspitManager;

            Pitanje pitanje = repoPitanje.FindById(idPitanje);


            List<int> submitOdg = getSubmited(fc);
            

            List<int> tocniOdg = getTocni(pitanje);


            bool tocno = submitOdg.SequenceEqual(tocniOdg);

            foreach (PitanjeManager pit in im.Pitanja)
            {
                if (idPitanje == pit.Pitanje.IdPitanje)
                {
                    if (tocno)
                    {
                        pit.Tocno = 1;
                    }
                    pit.Odgovoreno = 1;
                }
            }

            Pitanje next = new Pitanje();

            foreach (PitanjeManager pit in im.Pitanja)
            {
                if (pit.Odgovoreno == 0)
                {
                    next = pit.Pitanje;
                    break;
                }
                
            }

            if (next != null)
            {
                ViewBag.IdPitanje = next.IdPitanje;
                ViewBag.Tekst = next.Tekst;
            }

            bool sveOdg = ProvjeriPitanja(im);

            if (sveOdg)
            {
                Session["Kraj"] = 1;
            }

            Session["Ispit"] = im;

            return View(im);

        }

        private List<int> getTocni(Pitanje pitanje)
        {
            List<int> tocniOdg = new List<int>();

            foreach (Odgovor odg in pitanje.Odgovors)
            {
                if (odg.Tocno == 1)
                {
                    tocniOdg.Add(odg.IdOdgovor);
                }
            }

            tocniOdg.Sort();
            return tocniOdg;
        }

        private List<int> getSubmited(FormCollection fc)
        {
            List<int> submitOdg = new List<int>();

            if (fc.Count > 1)
            {
                for (int i = 1; i < fc.Count; i++)
                {
                    submitOdg.Add(Int32.Parse(fc.AllKeys[i]));
                }
            }

            submitOdg.Sort();
            return submitOdg;

        }

        [HttpPost]
        public ActionResult Kraj(FormCollection fc)
        {

            IspitManager im = Session["Ispit"] as IspitManager;
            int brojPitanja = im.Pitanja.Count;
            Rezultat rez = new Rezultat();

            int brojTocnih = getBrojTocnih(im);


            double postotak = (double)brojTocnih / (double)brojPitanja;
            double post = postotak * 100;

            Ispit ispit = repoIspit.FindById(im.IdIspit);

            double uvjet = (double)ispit.UvjetProlaza;

            if (post >= uvjet)
            {
                ViewBag.Tekst = "Prosli ste ispit!";
                rez.Prolaz = 1;
            }
            else
            {
                ViewBag.Tekst = "Pali ste ispit!";
                rez.Prolaz = 0;
            }

            Random rnd = new Random();
            rez.IdRezultat = rnd.Next(1, 9999);

            rez.Vrijeme = DateTime.Now;
            rez.BrojBodova = brojTocnih;
            rez.Postotak = (decimal)post;
            rez.KorisnikId = Int32.Parse(Session["UserID"].ToString());
            rez.IspitId = im.IdIspit;

            db.Rezultats.Add(rez);
            db.SaveChanges();


            return View();
            
        }

        private int getBrojTocnih(IspitManager im)
        {
            int brojTocnih = 0;

            foreach (PitanjeManager item in im.Pitanja)
            {
                if (item.Tocno == 1)
                {
                    brojTocnih++;
                }
            }

            return brojTocnih;
        }

        private bool ProvjeriPitanja(IspitManager im)
        {
            int brojSve = im.Pitanja.Count;
            int brojOdg = 0;

            foreach (PitanjeManager pm in im.Pitanja)
            {
                if (pm.Odgovoreno == 1)
                {
                    brojOdg++;
                }
            }

            if (brojSve == brojOdg)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

IspitiNRAKO/Views/MojIspit/Index.cshtml
@model IEnumerable<IspitiNRAKO.Ispit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Moji ispiti</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Datum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trajanje)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UvjetProlaza)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trajanje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UvjetProlaza)
            </td>
            <td>
                @Html.ActionLink("Start", "Start", new { id = item.IdIspit })
                
            </td>
        </tr>
    }

</table>

IspitiNRAKO/Views/MojIspit/Kraj.cshtml
@{
    ViewBag.Title = "Kraj";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Tekst</h2>

IspitiNRAKO/Views/MojIspit/Odgovori.cshtml
@model IspitiNRAKO.Models.IspitManager
@{
    ViewBag.Title = "Odgovori";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pitanja</title>
    
</head>
<body>
    

    <div>
        <h2 id="countdown"></h2>
    </div>
    <br />

    <div style="float:left">
        <ul>
            @{int counter = 1; }
            @foreach (IspitiNRAKO.Models.PitanjeManager item in Model.Pitanja)
            {
                if (item.Odgovoreno == 0)
                {
                    <li>
                        @Html.ActionLink("Pitanje " + counter, "Odgovori", new { id = item.Pitanje.IdPitanje }, new { @class = "btn btn-primary" })
                    </li>
                }
                else
                {
                    <li>
                        Pitanje @counter
                    </li>
                }
                counter++;
            }
        </ul>
    </div>
    
    
    @using (Html.BeginForm())
    {
        <div class="form-horizontal" style="float:left; margin-left:100px">
            <ul>
                <h3>@ViewBag.Tekst</h3>
                @foreach (IspitiNRAKO.Models.PitanjeManager item in Model.Pitanja)
                {
                    if (item.Pitanje.IdPitanje == ViewBag.IdPitanje)
                    {
                        @Html.Hidden("idPitanje", item.Pitanje.IdPitanje)
                        foreach (IspitiNRAKO.Odgovor odgovor in item.Pitanje.Odgovors)
                        {
                            <li>
                                @odgovor.Tekst
                                <input type="checkbox" id=@odgovor.IdOdgovor.ToString() name=@odgovor.IdOdgovor.ToString() value="false"  />
                            </li>
                        }
                    }
                }
            </ul>
        </div>
        if (Int32.Parse(Session["Kraj"].ToString()) != 1)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Odgovori" class="btn btn-default" />
                </div>
            </div>
        }

    }
    @if (Int32.Parse(Session["Kraj"].ToString()) == 1)
    {
        using (Html.BeginForm("Kraj", "MojIspit"))
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Zavrsi" class="btn btn-default" />
                </div>
            </div>
        }
    }

    @Scripts.Render("~/bundles/jquery")
    <script>
            var dt = '@Session["EndDate"]';
            var dateAr = dt.split('-');
            var newDate = dateAr[1] + '/' + dateAr[0] + '/' + dateAr[2];

            var end = new Date(dateAr[1] + '/' + dateAr[0] + '/' + dateAr[2]);

            var _second = 1000;
            var _minute = _second * 60;
            var _hour = _minute * 60;
            var _day = _hour * 24;
            var timer;

            function showRemaining() {
                var now = new Date();
                var distance = end - now;
                if (distance < 0) {
                    clearInterval(timer);
                    document.getElementById('countdown').innerHTML = 'Vrijeme isteklo!';
                    window.location.href = '/Login/Login';

                    return;
                }
                var days = Math.floor(distance / _day);
                var hours = Math.floor((distance % _day) / _hour);
                var minutes = Math.floor((distance % _hour) / _minute);
                var seconds = Math.floor((distance % _minute) / _second);

                //document.getElementById('countdown').innerHTML = days + 'days ';
                //document.getElementById('countdown').innerHTML = hours + 'hrs ';
                document.getElementById('countdown').innerHTML = minutes + 'mins ';
                document.getElementById('countdown').innerHTML += seconds + 'secs';
            }

            timer = setInterval(showRemaining, 1000);
    </script>


</body>
</html>

IspitiNRAKO/Views/MojIspit/Start.cshtml
@model IspitiNRAKO.Models.IspitManager

@{
    ViewBag.Title = "Start";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pitanja</title>
</head>
<body>
    <h2>Odaberite pitanje za početak ispita</h2>

    <div>
        <ul>
            @{int counter = 1; }
            @foreach (IspitiNRAKO.Models.PitanjeManager item in Model.Pitanja)
            {
                <li>
                    @Html.ActionLink("Pitanje " + counter, "Odgovori", new { id = item.Pitanje.IdPitanje}, new { @class = "btn btn-primary" })
                </li>
                counter++;
            }
        </ul>
    </div>
    
</body>
</html>