IspitiNRAKO/Controllers/PitanjeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IspitiNRAKO;
using IspitiNRAKO.CustomAttributes;
using IspitiNRAKO.Repozitorij;

namespace IspitiNRAKO.Controllers
{
    [LoginAdmins]
    public class PitanjeController : Controller
    {
        PitanjeRepozitorij repo = new PitanjeRepozitorij();

        // GET: Pitanje
        public ActionResult Index()
        {

            return View(repo.GetAll);
        }

        // GET: Pitanje/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = repo.FindById(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }
            return View(pitanje);
        }

        public ActionResult Odgovor(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = repo.FindById(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }

            return RedirectToAction("Prikaz", "Odgovor", new { idPitanje = id });
        }

        // GET: Pitanje/Create
        public ActionResult Create()
        {

            ViewBag.SkupPitanjaId = repo.SkupPitanjaList();
            ViewBag.VrstaPitanjaId = repo.VrstaPitanjaList();
            return View();
        }

        // POST: Pitanje/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPitanje,Tekst,Tezina,Aktivno,VrstaPitanjaId,SkupPitanjaId")] Pitanje pitanje)
        {
            if (ModelState.IsValid)
            {
                repo.Add(pitanje);
                repo.Save();
                return RedirectToAction("Index");
            }
            ViewBag.SkupPitanjaId = repo.SkupPitanjaList(pitanje.SkupPitanjaId);
            ViewBag.VrstaPitanjaId = repo.VrstaPitanjaList(pitanje.VrstaPitanjaId);
            return View(pitanje);
        }

        // GET: Pitanje/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = repo.FindById(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }
            ViewBag.SkupPitanjaId = repo.SkupPitanjaList(pitanje.SkupPitanjaId);
            ViewBag.VrstaPitanjaId = repo.VrstaPitanjaList(pitanje.VrstaPitanjaId);
            return View(pitanje);
        }

        // POST: Pitanje/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPitanje,Tekst,Tezina,Aktivno,VrstaPitanjaId,SkupPitanjaId")] Pitanje pitanje)
        {
            if (ModelState.IsValid)
            {
                repo.Update(pitanje);
                repo.Save();
                return RedirectToAction("Index");
            }
            ViewBag.SkupPitanjaId = repo.SkupPitanjaList(pitanje.SkupPitanjaId);
            ViewBag.VrstaPitanjaId = repo.VrstaPitanjaList(pitanje.VrstaPitanjaId);
            return View(pitanje);
        }

        // GET: Pitanje/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pitanje pitanje = repo.FindById(id);
            if (pitanje == null)
            {
                return HttpNotFound();
            }
            return View(pitanje);
        }

        // POST: Pitanje/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pitanje pitanje = repo.FindById(id);
            repo.Delete(pitanje);
            repo.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IspitiNRAKO/Controllers/SkupPitanjaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IspitiNRAKO;
using IspitiNRAKO.CustomAttributes;
using IspitiNRAKO.Repozitorij;

namespace IspitiNRAKO.Controllers
{
    [LoginAdmins]
    public class SkupPitanjaController : Controller
    {

        SkupPitanjaRepozitorij repo = new SkupPitanjaRepozitorij();

        // GET: SkupPitanja
        public ActionResult Index()
        {
            return View(repo.GetAll);
        }

        // GET: SkupPitanja/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SkupPitanja skupPitanja = repo.FindById(id);
            if (skupPitanja == null)
            {
                return HttpNotFound();
            }
            return View(skupPitanja);
        }

        // GET: SkupPitanja/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SkupPitanja/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSkupPitanja,Naziv")] SkupPitanja skupPitanja)
        {
            if (ModelState.IsValid)
            {
                repo.Add(skupPitanja);
                repo.Save();
                return RedirectToAction("Index");
            }

            return View(skupPitanja);
        }

        // GET: SkupPitanja/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SkupPitanja skupPitanja = repo.FindById(id);
            if (skupPitanja == null)
            {
                return HttpNotFound();
            }
            return View(skupPitanja);
        }

        // POST: SkupPitanja/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdSkupPitanja,Naziv")] SkupPitanja skupPitanja)
        {
            if (ModelState.IsValid)
            {
                repo.Update(skupPitanja);
                repo.Save();
                return RedirectToAction("Index");
            }
            return View(skupPitanja);
        }

        // GET: SkupPitanja/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SkupPitanja skupPitanja = repo.FindById(id);
            if (skupPitanja == null)
            {
                return HttpNotFound();
            }
            return View(skupPitanja);
        }

        // POST: SkupPitanja/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            SkupPitanja skupPitanja = repo.FindById(id);
            repo.Delete(skupPitanja);
            repo.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IspitiNRAKO/Views/SkupPitanja/Create.cshtml
@model IspitiNRAKO.SkupPitanja

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dodavanje nove grupe pitanja</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Skupina pitanja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kreiraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Natrag", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IspitiNRAKO/Views/SkupPitanja/Delete.cshtml
@model IspitiNRAKO.SkupPitanja

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Brisanje</h2>

<h3>Želite li obrisati skupinu pitanja?</h3>
<div>
    <h4>SkupPitanja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Brisi" class="btn btn-default" /> |
            @Html.ActionLink("Natrag", "Index")
        </div>
    }
</div>

IspitiNRAKO/Views/SkupPitanja/Details.cshtml
@model IspitiNRAKO.SkupPitanja

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SkupPitanja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdSkupPitanja }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IspitiNRAKO/Views/SkupPitanja/Edit.cshtml
@model IspitiNRAKO.SkupPitanja

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Uređivanje</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Skupina pitanja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdSkupPitanja)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Natrag", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IspitiNRAKO/Views/SkupPitanja/Index.cshtml
@model IEnumerable<IspitiNRAKO.SkupPitanja>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Skupine pitanja</h2>

<p>
    @Html.ActionLink("Dodaj novu skupinu pitanja", "Create")
</p>
<p>
    @Html.ActionLink("Pregled pitanja", "Index", "Pitanje")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Naziv)
        </td>
        <td>
            @Html.ActionLink("Uredi", "Edit", new { id=item.IdSkupPitanja }) |
            @Html.ActionLink("Brisi", "Delete", new { id=item.IdSkupPitanja })
        </td>
    </tr>
}

</table>